name: build and push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # daily at midnight
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE: silverblue

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fedora-version: [ 37 ]
        drivers: [none, nvidia]
        include:
          - fedora-version: 37
            is-latest: true
            is-stable: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          tags=()

          base_tag="${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ matrix.fedora-version }}"

          if [[ "${{ matrix.drivers }}" != "none" ]]; then
            base_tag="${base_tag}-${{ matrix.drivers }}"
          fi

          if [[ "${{ matrix.is-stable }}" ]]; then
            tags+=("${base_tag}-stable")
          fi

          if [[ "${{ matrix.is-latest }}" ]]; then
            tags+=("${base_tag}-latest")
          fi

          tags+=("${base_tag}-${GITHUB_SHA::8}")

          echo "tags=${tags[*]}" >> $GITHUB_ENV
          echo "Generated tags: ${tags[*]}"

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Rewrite the above using Docker instead of Buildah
      - name: Build image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          target: drivers-${{ matrix.drivers }}
          file: ./Containerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ join(steps.generate-tags.outputs.tags, ',') }}
          build-args: |
            FEDORA_VERSION=${{ matrix.fedora-version }}

      - name: Set up Cosign
        if: github.ref == 'refs/heads/main'
        uses: sigstore/cosign-installer@v2

      - name: Write cosign key
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > .certs/cosign.key
          chmod 600 cosign.key

      - name: Sign image
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          cosign sign -key .certs/cosign.key ${{ env.REGISTRY }}/${{ env.IMAGE }}:{$DIGEST}
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}

      - name: Verify image
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          cosign verify -key .certs/cosign.pub ${{ env.REGISTRY }}/${{ env.IMAGE }}
